
# Définition d'une tâche pour déployer les pages GitLab
pages:
  # N'utiliser que l'image d'un conteneur officiel pour GitLab CI/CD
  image: alpine:latest
  
  # Définition de la variable d'environnement CI_PAGES_DOMAIN pour régler le domaine de la page
  variables:
    CI_PAGES_DOMAIN: "welcome-to-the-wired.gitlab.io"

  # Définition des étapes de la tâche
  stage: deploy
  script:
    - apk add --no-cache git
    - git config --global user.name "$GITLAB_USER_NAME"
    - git config --global user.email "$GITLAB_USER_EMAIL"
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@${CI_REPOSITORY_URL#*@} public
    - mv public/* ./
    - git remote add pages "https://${CI_PAGES_DOMAIN}:x-oauth-basic@gitlab.com/${CI_PROJECT_PATH}.git"
    - git push --force pages HEAD:master
  only:
    - main